version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      # Update these with the variables set in the .env file
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myProject
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  paysplit:
    build: .
    container_name: myProject
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  my_data:
